# -*- coding: utf-8 -*-
import io,json
D=json.load(io.open('out/sweep/data.json',encoding='utf-8'))
d=D['dist']
def oku(v): return ('+' if v>=0 else '−')+('%.2f'%abs(v))
def pct(v): return '%.1f%%'%(v*100)
def com(v): return '{:,}'.format(v)
W=520
def bar(v,mx,w=W): return max(2,int(round(v/mx*w))) if mx else 2

mx=max(h['n'] for h in D['hist'])
hist=''.join(
 '<tr><td class="k">%s 〜 %s</td><td class="b"><span class="r" style="width:%dpx"></span><span class="s" style="width:%dpx"></span></td><td class="n">%s</td><td class="n rr">%s</td></tr>'
 %(oku(h['lo']),oku(h['lo']+0.5),bar(h['ruin'],mx),bar(h['n']-h['ruin'],mx) if h['n']-h['ruin'] else 0,com(h['n']),com(h['ruin']) if h['ruin'] else '—')
 for h in D['hist'])
emx=max(e['v'] for e in D['eta'])
eta=''.join('<tr><td class="k">%s</td><td class="b"><span class="%s" style="width:%dpx"></span></td><td class="n">%s</td></tr>'
 %(e['name'],'env' if e['env'] else 'dial',bar(e['v'],emx,460),'%.2f%%'%(e['v']*100)) for e in D['eta'])
econ=''.join('<tr%s><td>%s</td><td class="n">%s</td><td class="n">%s</td><td class="n">%s</td><td class="n">%s</td></tr>'
 %(' class="base"' if e['name']=='成長型' else '',e['name'],oku(e['min']),oku(e['med']),oku(e['max']),pct(e['ruin'])) for e in D['econ'])
def dial(name):
    return ''.join('<tr><td>%s</td><td class="n">%s</td><td class="n">%s</td></tr>'%(r['lv'],oku(r['med']),pct(r['ruin'])) for r in D['dials'][name])
heat=''.join('<tr><td>%s</td><td>%s</td><td class="n">%s</td><td class="n">%s</td></tr>'
 %(h['住まい'],h['生活費'],oku(h['med']),pct(h['ruin'])) for h in D['heat'])
res=D['resort']
rm=''.join('<tr><td>%s</td><td class="n">%s</td></tr>'%(m['name'],com(m['n'])) for m in res['byMeasure'])
re_=''.join('<tr><td>%s</td><td class="n">%s</td><td class="n">%s</td></tr>'%(e['name'],com(e['used']),pct(e['used']/e['n'])) for e in res['byEconomy'])
ra=D.get('ruinAge',{}); ry=res.get('years',{})
axes=[('経済',7,'no','7 published economies'),('金融危機',7,'no','none, or a −20% crash in one of five years, or two consecutive years'),
      ('生活費',3,'yes','the 家計調査 average for the head\'s age, or ±¥40k a month'),
      ('年金受給開始',4,'yes','as now (70) / 65 / 70 / 75'),
      ('住まい',2,'yes','buy the 70㎡ flat in 2023, or rent the same size for life')]
axrows=''.join('<tr><td>%s</td><td class="n">%d</td><td>%s</td><td>%s</td></tr>'%(a,n,c,t) for a,n,c,t in axes)

html='''<!-- generated by tools/sweep + examples/build.py; do not edit by hand -->
<title>%(n)s ways this household could go</title>
<style>
:root{color-scheme:light;--plane:#f3f4f5;--surface:#fcfcfb;--ink:#0b0b0b;--ink2:#52514e;--muted:#7d7c76;
--rule:rgba(11,11,11,.12);--s1:#2a78d6;--s2:#eb6834;--crit:#d03b3b;--band:rgba(42,120,214,.07)}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark;--plane:#0c0c0c;--surface:#1a1a19;
--ink:#fff;--ink2:#c3c2b7;--muted:#898781;--rule:rgba(255,255,255,.14);--s1:#3987e5;--s2:#d95926;--crit:#d03b3b;--band:rgba(57,135,229,.10)}}
:root[data-theme="dark"]{color-scheme:dark;--plane:#0c0c0c;--surface:#1a1a19;--ink:#fff;--ink2:#c3c2b7;--muted:#898781;
--rule:rgba(255,255,255,.14);--s1:#3987e5;--s2:#d95926;--crit:#d03b3b;--band:rgba(57,135,229,.10)}
*{box-sizing:border-box}
body{margin:0;background:var(--plane);color:var(--ink);font:16px/1.75 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.wrap{max-width:1000px;margin:0 auto;padding:0 24px 96px}
header{padding:64px 0 32px}.kicker{font-size:.75rem;letter-spacing:.2em;color:var(--muted);margin:0 0 18px}
h1{font-size:clamp(2rem,5vw,3.2rem);line-height:1.2;margin:0 0 18px;font-weight:600}
.lede{font-size:1.05rem;color:var(--ink2);margin:0;max-width:38em}
.tiles{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:var(--rule);border:1px solid var(--rule);margin:40px 0 0}
@media(min-width:760px){.tiles{grid-template-columns:repeat(4,minmax(0,1fr))}}
.tile{background:var(--surface);padding:18px 20px}
.tile .v{font-size:1.9rem;line-height:1.1;font-weight:600;display:block;font-variant-numeric:tabular-nums}
.tile .k{font-size:.8rem;color:var(--ink2);margin-top:6px;display:block;line-height:1.5}
.tile.alarm .v{color:var(--crit)}
section{padding:48px 0 0}h2{font-size:1.5rem;margin:0 0 6px;font-weight:600}
h2+.sub{color:var(--muted);font-size:.85rem;margin:0 0 20px}
p{margin:0 0 1.1em}hr{height:1px;background:var(--rule);border:0;margin:48px 0 0}
figure{margin:26px 0 30px;background:var(--surface);border:1px solid var(--rule);padding:20px}
figcaption{font-size:.82rem;color:var(--ink2);margin-top:12px;line-height:1.65}
.scroll{overflow-x:auto}
table{border-collapse:collapse;width:100%%;font-size:.88rem}
th,td{padding:8px 11px;text-align:left;border-bottom:1px solid var(--rule);vertical-align:baseline}
thead th{font-size:.76rem;color:var(--muted);font-weight:600;white-space:nowrap}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}
tr.base td{background:var(--band)}
td.k{white-space:nowrap;font-variant-numeric:tabular-nums;color:var(--ink2)}
td.b{width:%(W)dpx}td.b span{display:inline-block;height:12px;vertical-align:middle;border-radius:2px}
td.b .r{background:var(--crit)}td.b .s{background:var(--s1)}
td.b .env{background:var(--s2)}td.b .dial{background:var(--s1)}
td.rr{color:var(--crit)}
.callout{border-left:3px solid var(--s1);padding:2px 0 2px 18px;margin:26px 0}
.callout.warn{border-left-color:var(--crit)}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:var(--band);padding:.1em .35em;border-radius:3px;font-size:.92em}
footer{margin-top:64px;padding-top:22px;border-top:1px solid var(--rule);font-size:.82rem;color:var(--muted)}
</style>
<div class="wrap">
<header>
<p class="kicker">lifeplan / full factorial sweep / example</p>
<h1>%(n)s ways this household could go</h1>
<p class="lede">Five axes, every combination, each one a complete plan run to the year the earner turns 100.
The answer spreads from %(min)s to %(max)s hundred-million yen. The point of running all of them is not
to count how many fail — that number says more about which scenarios were put in than about the household —
but to see <strong>which axis moves the answer</strong>.
<strong>The household is invented</strong> — see the caveat at the foot.</p>
</header>
<div class="tiles">
<div class="tile"><span class="v">%(n)s</span><span class="k">cells, each a full plan</span></div>
<div class="tile"><span class="v">%(etaTop)s</span><span class="k">of the spread is where the household lives</span></div>
<div class="tile"><span class="v">%(etaMain)s</span><span class="k">of the spread explained by the five axes alone</span></div>
<div class="tile"><span class="v">%(resortUsed)s</span><span class="k">cells turned the home into cash</span></div>
</div>
<hr>
<section>
<h2>What was varied</h2>
<p class="sub">One decision per axis. The first level of every axis is the plan as written</p>
<p>A bundle like "carry on as now" moves several things at once, so a row of results can only say
<em>which bundle</em> was chosen — never which dial did the work. Splitting the bundles into one
decision per axis and running the full product answers that.</p>
<figure><div class="scroll"><table>
<thead><tr><th>Axis</th><th class="n">Levels</th><th>Chosen?</th><th>What the levels are</th></tr></thead>
<tbody>%(axes)s</tbody></table></div>
<figcaption>7 × 7 × 3 × 4 × 2 = <b>%(n)s</b>. <b>Each axis multiplies the cost</b>, so choosing the axes
is choosing the running time.</figcaption></figure>
</section>
<hr>
<section>
<h2>How wide it spreads</h2>
<p class="sub">Net worth in the final year, in today's prices, hundred-million yen</p>
<p><strong>Assets stop at zero and never go negative.</strong> A plan that cannot pay records the amount it
could not pay as a shortfall and carries on. Read straight, every ruined cell would sit at zero and the
measure would go flat exactly where it matters most. So the response is <strong>assets less cumulative
shortfall</strong>, which can go negative.</p>
<figure><div class="scroll"><table>
<thead><tr><th>Band</th><th class="b">Cells</th><th class="n">n</th><th class="n">of which ruined</th></tr></thead>
<tbody>%(hist)s</tbody></table></div>
<figcaption>min <b>%(min)s</b> / lower quartile <b>%(q1)s</b> / median <b>%(med)s</b> / upper quartile <b>%(q3)s</b> / max <b>%(max)s</b>.
Blue is solvent, red ran out on the way. <b>There is no gap between ruin and "just made it"</b> — it gets worse continuously.</figcaption></figure>
</section>
<hr>
<section>
<h2>What actually moves it</h2>
<p class="sub">Variance explained, η². The share of the spread each axis accounts for</p>
<p>A balanced full factorial lets the spread be split cleanly by axis. <strong>This is the most honest measure of
sensitivity</strong> — moving one factor at a time gives a different answer depending on where the others were parked.</p>
<figure><div class="scroll"><table>
<thead><tr><th>Axis</th><th class="b">Share of the spread</th><th class="n">η²</th></tr></thead>
<tbody>%(eta)s</tbody></table></div>
<figcaption>Orange is what the household cannot choose; blue is a dial it can. Main effects total <b>%(etaMain)s</b>;
the rest is interaction between axes.</figcaption></figure>
</section>
<hr>
<section>
<h2>The economy is not a choice</h2>
<p class="sub">Fixing the economy, then swinging every dial from best to worst</p>
<figure><div class="scroll"><table>
<thead><tr><th>Economy</th><th class="n">worst</th><th class="n">median</th><th class="n">best</th><th class="n">ruin rate</th></tr></thead>
<tbody>%(econ)s</tbody></table></div>
<figcaption>Hundred-million yen, today's prices. The shaded row is the economy the plan as written assumes.</figcaption></figure>
<div class="callout warn"><strong>In the harshest economies every combination fails.</strong>
No setting of the dials keeps this household solvent there. That is the sweep's most useful output:
it says plainly where the problem is not something the household can fix by choosing differently.</div>
</section>
<hr>
<section>
<h2>The dials, one at a time</h2>
<p class="sub">Median net worth and ruin rate for each level</p>
<figure><div class="scroll"><table><thead><tr><th>Housing</th><th class="n">median</th><th class="n">ruin</th></tr></thead><tbody>%(dial_housing)s</tbody></table></div>
<figcaption>Where the household lives is the largest dial it controls — larger than the economy.</figcaption></figure>
<figure><div class="scroll"><table><thead><tr><th>Living cost</th><th class="n">median</th><th class="n">ruin</th></tr></thead><tbody>%(dial_living)s</tbody></table></div>
<figcaption>Spending is a dial, but a smaller one than the roof over the household.</figcaption></figure>
<figure><div class="scroll"><table><thead><tr><th>Pension start</th><th class="n">median</th><th class="n">ruin</th></tr></thead><tbody>%(dial_pension)s</tbody></table></div>
<figcaption>Deferring raises the median, but the years spent waiting have to be crossed by drawing down.</figcaption></figure>
<figure><div class="scroll"><table><thead><tr><th>Crash</th><th class="n">median</th><th class="n">ruin</th></tr></thead><tbody>%(dial_crisis)s</tbody></table></div>
<figcaption>The same fall costs different amounts depending on when it lands and how much is held at the time.</figcaption></figure>
</section>
<hr>
<section>
<h2>Housing against living cost</h2>
<p class="sub">Every other axis swept inside each square</p>
<figure><div class="scroll"><table>
<thead><tr><th>Housing</th><th>Living cost</th><th class="n">median</th><th class="n">ruin rate</th></tr></thead>
<tbody>%(heat)s</tbody></table></div>
<figcaption>Each row aggregates every combination of the remaining three axes.</figcaption></figure>
</section>
<hr>
<section>
<h2>The home is the last thing left</h2>
<p class="sub">When a plan cannot pay, it either sells and rents, or borrows against the house</p>
<p>Both measures need the mortgage repaid first: a house already pledged cannot be pledged again,
and selling means clearing the loan out of the proceeds. <strong>The plan builds both and takes whichever
is better</strong> — it is not a choice the household makes.</p>
<figure><div class="scroll"><table><thead><tr><th>Measure</th><th class="n">times taken</th></tr></thead><tbody>%(resortM)s</tbody></table></div>
<figcaption>Taken in <b>%(resortUsed)s</b> cells, first at <b>%(resortMin)s</b>, median <b>%(resortMed)s</b>, last at <b>%(resortMax)s</b>.</figcaption></figure>
<figure><div class="scroll"><table><thead><tr><th>Economy</th><th class="n">cells that used it</th><th class="n">share</th></tr></thead><tbody>%(resortE)s</tbody></table></div>
<figcaption><b>Whether the home has to be sold is decided by the economy long before the household chooses anything.</b></figcaption></figure>
</section>
<hr>
<section>
<h2>What this does not answer</h2>
<p><strong>How likely ruin is.</strong> %(ruinN)s of the %(n)s combinations fail, which is %(ruinPct)s of them —
and <b>that figure means nothing on its own</b>. It is the share of the scenarios that were put in, not a
probability: load the sweep with pessimistic economies and it rises, load it with optimistic ones and it falls.
Nobody can grade the scenarios accurately enough for the share to become a chance. The seven economies and the
seven crashes here are counted equally, and they are not equally likely. <b>Read the axes, not the count.</b></p>
<p><strong>Asset allocation by age.</strong> Contributions are fixed to one execution policy; nothing here varies the
mix of shares and bonds. Knowing that a crash hurts most just before drawdown does not tell you what to do about it.</p>
<p><strong>Care, redundancy, inheritance.</strong> None of them is an axis.</p>
<p><strong>Anything about a real household.</strong> Every figure describes an invented one.</p>
</section>
<footer>
<p>Generated by <code>tools/sweep</code>, which passes overrides to <code>plan.Build</code> rather than writing
%(n)s manifests. Results in <code>out/sweep/cells.tsv</code>. Reproduce with
<code>go run ./tools/sweep &amp;&amp; python3 examples/analyse.py &amp;&amp; python3 examples/build.py</code>.</p>
<p><strong>The household in this report does not exist.</strong> Nobody lives at these figures. But they are not
invented either: the pay comes from the 民間給与実態統計調査 by age band, the spouse's from the
賃金構造基本統計調査 hourly rate for part-time women, the spending from the 家計調査 for the head's age band,
and the rent and the price from the going rate for a 70㎡ flat in 八王子市. Each one is cited in
<code>data/controllable/README.md</code>. <b>The dial choices, the
statutory rules and the economic projections are real</b>; only the household is not. Amounts are real terms,
discounted to the plan's first year. Pension levels follow the 2024 財政検証; the crash severity is a chosen
round figure, not a property of any particular portfolio.</p>
</footer>
</div>
'''%{'n':com(D['n']),'ruinN':com(d['ruinN']),'ruinPct':pct(d['ruin']),'min':oku(d['min']),'max':oku(d['max']),
     'med':oku(d['med']),'q1':oku(d['q1']),'q3':oku(d['q3']),'etaMain':'%.1f%%'%(D['etaMainSum']*100),'etaTop':'%.0f%%'%(D['eta'][0]['v']*100),
     'hist':hist,'eta':eta,'econ':econ,'heat':heat,'axes':axrows,'W':W,
     'dial_housing':dial('住まい'),'dial_living':dial('生活費'),'dial_pension':dial('年金受給開始'),'dial_crisis':dial('金融危機'),
     'resortM':rm,'resortE':re_,'resortUsed':com(res['used']),
     'resortMin':ry.get('min','—'),'resortMed':ry.get('med','—'),'resortMax':ry.get('max','—')}
io.open('examples/sweep-report.html','w',encoding='utf-8').write(html)
print('wrote examples/sweep-report.html (%d bytes)'%len(html))
